# Generated by Django 4.0 on 2021-12-23 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_emirates_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact_number',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emirates_id',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.SmallIntegerField(),
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.task')),
            ],
        ),
    ]
