# Generated by Django 4.0 on 2021-12-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_department_supplier_alter_subtask_task_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='contact_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emirates_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.PositiveIntegerField(),
        ),
    ]
