# Generated by Django 4.0 on 2021-12-25 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_empphotos_remove_employee_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmpPhotos',
        ),
    ]
