# Generated by Django 4.0 on 2021-12-28 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_brand_fuelcard_model_user_brandsupplier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brandsupplier',
            old_name='branding_id',
            new_name='brand_id',
        ),
        migrations.CreateModel(
            name='VehicleDetail',
            fields=[
                ('plate_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('ModelYear', models.CharField(max_length=4)),
                ('Equipment', models.CharField(max_length=30)),
                ('Chess', models.CharField(max_length=50)),
                ('PlateCode', models.CharField(max_length=10)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('location', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('brandsupplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='tracker.brandsupplier')),
                ('emirates_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emirates', to='tracker.emirates')),
                ('fuelcard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuelcards', to='tracker.fuelcard')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='tracker.model')),
                ('subdepartment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdepartment', to='tracker.subdepartment')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='tracker.supplier')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicletype', to='tracker.vehicletype')),
            ],
        ),
    ]
