# Generated by Django 4.0 on 2021-12-28 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_fleettouser_fleettouserimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fleettouser',
            old_name='EntryDate',
            new_name='entry_date',
        ),
        migrations.RenameField(
            model_name='fleettouser',
            old_name='fueltank',
            new_name='fuel_tank',
        ),
        migrations.RenameField(
            model_name='fleettouser',
            old_name='Time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='vehicledetail',
            old_name='Chess',
            new_name='chess',
        ),
        migrations.RenameField(
            model_name='vehicledetail',
            old_name='Equipment',
            new_name='equipment',
        ),
        migrations.RenameField(
            model_name='vehicledetail',
            old_name='ModelYear',
            new_name='model_year',
        ),
        migrations.RenameField(
            model_name='vehicledetail',
            old_name='plate_number',
            new_name='plate_no',
        ),
        migrations.RenameField(
            model_name='vehicledetail',
            old_name='PlateCode',
            new_name='platecode',
        ),
        migrations.RemoveField(
            model_name='fleettouser',
            name='subtask_id',
        ),
    ]
