# Generated by Django 4.0 on 2022-03-30 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleDetail',
        ),
    ]
