# Generated by Django 4.0 on 2022-03-30 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_delete_vehicledetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_no', models.PositiveIntegerField()),
                ('model_year', models.CharField(max_length=4)),
                ('equipment', models.CharField(max_length=30)),
                ('chess', models.CharField(max_length=50)),
                ('platecode', models.CharField(max_length=10)),
                ('contract_start_date', models.DateField()),
                ('contract_end_date', models.DateField()),
                ('location', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('brandsupplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='tracker.brandsupplier')),
                ('emirates_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emirates', to='tracker.emirates')),
                ('fuelcard_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuelcards', to='tracker.fuelcard')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='tracker.model')),
                ('subdepartment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdepartment', to='tracker.subdepartment')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='tracker.supplier')),
                ('type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicletype', to='tracker.vehicletype')),
            ],
        ),
    ]
