# Generated by Django 4.0 on 2022-03-30 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_vehicledetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetail',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='tracker.location'),
        ),
    ]
