# Generated by Django 4.0 on 2022-03-30 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_alter_vehicledetail_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetail',
            name='supplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='tracker.supplier', verbose_name='Supplier'),
        ),
    ]
