# Generated by Django 4.0 on 2022-03-30 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_alter_vehicledetail_supplier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetail',
            name='brandsupplier_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='tracker.brandsupplier', verbose_name='Brand Supplier'),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='emirates_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emirates', to='tracker.emirates', verbose_name='Emirates'),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='fuelcard_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuelcards', to='tracker.fuelcard', verbose_name='Fuel Card'),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='tracker.model', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='subdepartment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subdepartment', to='tracker.subdepartment', verbose_name='Sub Department'),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicletype', to='tracker.vehicletype', verbose_name='Type'),
        ),
    ]
