# Generated by Django 4.0 on 2022-03-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_alter_vehicledetail_brandsupplier_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vehicledetail',
            unique_together={('plate_no', 'emirates_id', 'platecode')},
        ),
    ]
