# Generated by Django 4.0 on 2022-03-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_alter_vehicledetail_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetail',
            name='equipment',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='model_year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='platecode',
            field=models.PositiveIntegerField(),
        ),
    ]
