# Generated by Django 4.0 on 2022-04-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_alter_vehicledetail_equipment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledetail',
            name='equipment',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='vehicledetail',
            name='platecode',
            field=models.CharField(max_length=10),
        ),
    ]
