# Generated by Django 4.0 on 2022-04-15 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_fleet'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledetail',
            name='fleet_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet', to='tracker.fleet', verbose_name='Fleet'),
        ),
    ]
