# Generated by Django 4.0 on 2022-06-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_license'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photodetail', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
